# Generated by Django 4.0.1 on 2022-01-28 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89fe39ef-0efa-40e2-8bc6-0b607b74ea4d'), primary_key=True, serialize=False),
        ),
    ]
